# Generated by Django 6.0.2 on 2026-02-07 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('sub_category_name', models.CharField(max_length=200, null=True)),
                ('sub_sub_category_name', models.CharField(max_length=200, null=True)),
                ('category_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acf_tossup_per_period_count', models.PositiveIntegerField(default=20)),
                ('acf_bonus_per_period_count', models.PositiveIntegerField(default=20)),
                ('vhsl_bonus_per_period_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_name', models.CharField(max_length=200)),
                ('date_submitted', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TieBreakDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryEntryForDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acf_tossup_fraction', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('acf_bonus_fraction', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('vhsl_bonus_fraction', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('min_total_questions_in_period', models.PositiveIntegerField(null=True)),
                ('max_total_questions_in_period', models.PositiveIntegerField(null=True)),
                ('category_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.categoryentry')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.distribution')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('subcategory', models.TextField()),
                ('min_tossups', models.PositiveIntegerField(null=True)),
                ('min_bonuses', models.PositiveIntegerField(null=True)),
                ('max_tossups', models.PositiveIntegerField(null=True)),
                ('max_bonuses', models.PositiveIntegerField(null=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.distribution')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acf_tossup_cur', models.PositiveIntegerField(default=0)),
                ('acf_bonus_cur', models.PositiveIntegerField(default=0)),
                ('vhsl_bonus_cur', models.PositiveIntegerField(default=0)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.packet')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodWideCategoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acf_tossup_cur_across_periods', models.PositiveIntegerField(default=0)),
                ('acf_bonus_cur_across_periods', models.PositiveIntegerField(default=0)),
                ('vhsl_bonus_cur_across_periods', models.PositiveIntegerField(default=0)),
                ('acf_tossup_total_across_periods', models.PositiveIntegerField(null=True)),
                ('acf_bonus_total_across_periods', models.PositiveIntegerField(null=True)),
                ('vhsl_bonus_total_across_periods', models.PositiveIntegerField(null=True)),
                ('category_entry_for_distribution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qsub.categoryentryfordistribution')),
            ],
        ),
        migrations.CreateModel(
            name='OnePeriodCategoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acf_tossup_cur_in_period', models.PositiveIntegerField(default=0)),
                ('acf_bonus_cur_in_period', models.PositiveIntegerField(default=0)),
                ('vhsl_bonus_cur_in_period', models.PositiveIntegerField(default=0)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.period')),
                ('period_wide_category_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.periodwidecategoryentry')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodWideEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(max_length=200)),
                ('acf_tossup_cur', models.PositiveIntegerField(default=0)),
                ('acf_bonus_cur', models.PositiveIntegerField(default=0)),
                ('vhsl_bonus_cur', models.PositiveIntegerField(default=0)),
                ('acf_tossup_total', models.PositiveIntegerField(null=True)),
                ('acf_bonus_total', models.PositiveIntegerField(null=True)),
                ('vhsl_bonus_total', models.PositiveIntegerField(null=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.distribution')),
            ],
        ),
        migrations.AddField(
            model_name='periodwidecategoryentry',
            name='period_wide_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.periodwideentry'),
        ),
        migrations.AddField(
            model_name='period',
            name='period_wide_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.periodwideentry'),
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('host', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('num_packets', models.PositiveIntegerField()),
                ('max_acf_tossup_length', models.PositiveIntegerField(default=750)),
                ('max_acf_bonus_length', models.PositiveIntegerField(default=400)),
                ('max_vhsl_bonus_length', models.PositiveIntegerField(default=100)),
                ('char_count_ignores_pronunciation_guides', models.BooleanField(default=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.distribution')),
            ],
        ),
        migrations.AddField(
            model_name='periodwideentry',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionset'),
        ),
        migrations.AddField(
            model_name='packet',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionset'),
        ),
        migrations.CreateModel(
            name='DistributionPerPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('S-P', 'Science - physics'), ('S-C', 'Science - chemistry'), ('S-B', 'Science - biology'), ('S-O', 'Science - other'), ('L-AM', 'Literature - American'), ('L-EU', 'Literature - European'), ('L-BR', 'Literature - British'), ('L-W', 'Literature - World'), ('H-AM', 'History - American'), ('H-EU', 'History - European'), ('H-W', 'History - World'), ('R', 'Religion'), ('M', 'Myth'), ('P', 'Philosophy'), ('FA', 'Fine arts'), ('SS', 'Social science'), ('G', 'Geography'), ('O', 'Other'), ('PC', 'Pop culture')], max_length=10)),
                ('subcategory', models.CharField(max_length=10)),
                ('num_tossups', models.PositiveIntegerField()),
                ('num_bonuses', models.PositiveIntegerField()),
                ('question_set', models.ManyToManyField(to='qsub.questionset')),
            ],
        ),
        migrations.CreateModel(
            name='SetWideDistributionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tossups', models.PositiveIntegerField()),
                ('num_bonuses', models.PositiveIntegerField()),
                ('dist_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.distributionentry')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionset')),
            ],
        ),
        migrations.CreateModel(
            name='TieBreakDistributionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tossups', models.PositiveIntegerField(null=True)),
                ('num_bonuses', models.PositiveIntegerField(null=True)),
                ('dist_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.distributionentry')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionset')),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator', models.BooleanField(default=False)),
                ('send_mail_on_comments', models.BooleanField(default=False)),
                ('question_set_editor', models.ManyToManyField(related_name='editor', to='qsub.questionset')),
                ('question_set_writer', models.ManyToManyField(related_name='writer', to='qsub.questionset')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TossupHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tossup_text', models.TextField()),
                ('tossup_answer', models.TextField()),
                ('change_date', models.DateTimeField()),
                ('question_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionhistory')),
                ('question_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qsub.questiontype')),
                ('changer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.writer')),
            ],
        ),
        migrations.CreateModel(
            name='Tossup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tossup_text', models.TextField()),
                ('tossup_answer', models.TextField()),
                ('subtype', models.CharField(max_length=500)),
                ('time_period', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('locked', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('proofread', models.BooleanField(default=False)),
                ('read_carefully', models.BooleanField(default=False)),
                ('question_number', models.PositiveIntegerField(null=True)),
                ('search_question_content', models.TextField(default='')),
                ('search_question_answers', models.TextField(default='')),
                ('created_date', models.DateTimeField()),
                ('last_changed_date', models.DateTimeField()),
                ('edited_date', models.DateTimeField(null=True)),
                ('proofread_date', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qsub.distributionentry')),
                ('packet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qsub.packet')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qsub.period')),
                ('question_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qsub.questionhistory')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionset')),
                ('question_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qsub.questiontype')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.writer')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tossup_editor', to='qsub.writer')),
                ('proofreader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tossup_proofreader', to='qsub.writer')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=500)),
                ('can_view_others', models.BooleanField(default=False)),
                ('can_edit_others', models.BooleanField(default=False)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionset')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.writer')),
            ],
        ),
        migrations.AddField(
            model_name='questionset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='qsub.writer'),
        ),
        migrations.AddField(
            model_name='packet',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packet_creator', to='qsub.writer'),
        ),
        migrations.CreateModel(
            name='BonusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadin', models.CharField(max_length=500, null=True)),
                ('part1_text', models.TextField()),
                ('part1_answer', models.TextField()),
                ('part2_text', models.TextField(null=True)),
                ('part2_answer', models.TextField(null=True)),
                ('part3_text', models.TextField(null=True)),
                ('part3_answer', models.TextField(null=True)),
                ('change_date', models.DateTimeField()),
                ('question_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionhistory')),
                ('question_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qsub.questiontype')),
                ('changer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.writer')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadin', models.CharField(max_length=500, null=True)),
                ('part1_text', models.TextField()),
                ('part1_answer', models.TextField()),
                ('part2_text', models.TextField(null=True)),
                ('part2_answer', models.TextField(null=True)),
                ('part3_text', models.TextField(null=True)),
                ('part3_answer', models.TextField(null=True)),
                ('subtype', models.CharField(max_length=500)),
                ('time_period', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('locked', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('proofread', models.BooleanField(default=False)),
                ('read_carefully', models.BooleanField(default=False)),
                ('question_number', models.PositiveIntegerField(null=True)),
                ('search_question_content', models.TextField(default='')),
                ('search_question_answers', models.TextField(default='')),
                ('created_date', models.DateTimeField()),
                ('last_changed_date', models.DateTimeField()),
                ('edited_date', models.DateTimeField(null=True)),
                ('proofread_date', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qsub.distributionentry')),
                ('packet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qsub.packet')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qsub.period')),
                ('question_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qsub.questionhistory')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionset')),
                ('question_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qsub.questiontype')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.writer')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_editor', to='qsub.writer')),
                ('proofreader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_proofreader', to='qsub.writer')),
            ],
        ),
        migrations.CreateModel(
            name='WriterQuestionSetSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_all_new_comments', models.BooleanField(default=False)),
                ('email_on_all_new_questions', models.BooleanField(default=False)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionset')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.writer')),
            ],
        ),
        migrations.CreateModel(
            name='PerCategoryWriterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_new_questions', models.BooleanField(default=False)),
                ('email_on_new_comments', models.BooleanField(default=False)),
                ('distribution_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.distributionentry')),
                ('writer_question_set_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.writerquestionsetsettings')),
            ],
        ),
    ]
