# Generated by Django 6.0.2 on 2026-02-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0002_commentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='part1_difficulty',
            field=models.CharField(blank=True, choices=[('', '-'), ('e', 'Easy'), ('m', 'Medium'), ('h', 'Hard')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='bonus',
            name='part2_difficulty',
            field=models.CharField(blank=True, choices=[('', '-'), ('e', 'Easy'), ('m', 'Medium'), ('h', 'Hard')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='bonus',
            name='part3_difficulty',
            field=models.CharField(blank=True, choices=[('', '-'), ('e', 'Easy'), ('m', 'Medium'), ('h', 'Hard')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='bonushistory',
            name='part1_difficulty',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='bonushistory',
            name='part2_difficulty',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='bonushistory',
            name='part3_difficulty',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
