# Generated by Django 6.0.2 on 2026-06-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0003_bonus_part1_difficulty_bonus_part2_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='co_owners',
            field=models.ManyToManyField(blank=True, related_name='co_owned_sets', to='qsub.writer'),
        ),
    ]
