# Generated by Django 6.0.2 on 2026-06-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0004_questionset_co_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='bonuses_per_packet',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='questionset',
            name='tossups_per_packet',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.CreateModel(
            name='PacketizationEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('min_tossups', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('max_tossups', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('min_bonuses', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('max_bonuses', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionset')),
            ],
        ),
    ]
