# Generated by Django 6.0.2 on 2026-06-11 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0005_questionset_bonuses_per_packet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_path', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('num_tossups', models.PositiveIntegerField(default=0)),
                ('num_bonuses', models.PositiveIntegerField(default=0)),
                ('bonuses', models.ManyToManyField(blank=True, related_name='category_tags', to='qsub.bonus')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionset')),
                ('tossups', models.ManyToManyField(blank=True, related_name='category_tags', to='qsub.tossup')),
            ],
        ),
    ]
