# Generated by Django 6.0.2 on 2026-06-12 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0004_add_object_pk_is_removed_index'),
        ('qsub', '0006_categorytag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAnchor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_text', models.TextField()),
                ('prefix', models.CharField(blank=True, default='', max_length=100)),
                ('suffix', models.CharField(blank=True, default='', max_length=100)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anchor_info', to='django_comments.comment')),
            ],
        ),
    ]
