# Generated by Django 6.0.2 on 2026-06-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0007_commentanchor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='max_acf_bonus_length',
            field=models.PositiveIntegerField(default=650),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='max_acf_tossup_length',
            field=models.PositiveIntegerField(default=725),
        ),
    ]
