# Generated by Django 6.0.2 on 2026-06-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0008_alter_questionset_max_acf_bonus_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='tossups_only',
            field=models.BooleanField(default=False),
        ),
    ]
