# Generated by Django 6.0.2 on 2026-06-15 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0004_add_object_pk_is_removed_index'),
        ('qsub', '0009_questionset_tossups_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='django_comments.comment')),
                ('mentioned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='qsub.writer')),
            ],
        ),
        migrations.CreateModel(
            name='PacketGridLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('undo_data', models.TextField(default='[]')),
                ('undone', models.BooleanField(default=False)),
                ('changer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packet_grid_changes', to='qsub.writer')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionset')),
            ],
        ),
    ]
