# Generated by Django 6.0.2 on 2026-06-15 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0010_commentmention_packetgridlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField()),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionset')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_seen', to='qsub.writer')),
            ],
            options={
                'unique_together': {('writer', 'question_set')},
            },
        ),
    ]
