# Generated by Django 6.0.2 on 2026-06-17 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0012_commentresolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleIssueDismissal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=10)),
                ('question_id', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=40)),
                ('token', models.CharField(blank=True, default='', max_length=255)),
                ('dismissed_date', models.DateTimeField(auto_now_add=True)),
                ('dismissed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qsub.writer')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionset')),
            ],
            options={
                'unique_together': {('question_type', 'question_id', 'code', 'token')},
            },
        ),
    ]
