# Generated by Django 6.0.2 on 2026-06-17 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0013_styleissuedismissal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaytestSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(choices=[('web', 'Web'), ('discord', 'Discord')], default='web', max_length=20)),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playtest_sessions', to='qsub.writer')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playtest_sessions', to='qsub.questionset')),
            ],
        ),
        migrations.CreateModel(
            name='BonusResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, default='', max_length=200)),
                ('part1_correct', models.BooleanField(default=False)),
                ('part2_correct', models.BooleanField(default=False)),
                ('part3_correct', models.BooleanField(default=False)),
                ('total', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('web', 'Web'), ('discord', 'Discord')], default='web', max_length=20)),
                ('answered_date', models.DateTimeField(auto_now_add=True)),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='qsub.bonus')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_results', to='qsub.writer')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_results', to='qsub.playtestsession')),
            ],
        ),
        migrations.CreateModel(
            name='TossupBuzz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, default='', max_length=200)),
                ('buzz_word_index', models.PositiveIntegerField(default=0)),
                ('total_words', models.PositiveIntegerField(default=0)),
                ('char_position', models.PositiveIntegerField(default=0)),
                ('correct', models.BooleanField(default=False)),
                ('powered', models.BooleanField(default=False)),
                ('value', models.IntegerField(default=0)),
                ('answer_given', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('web', 'Web'), ('discord', 'Discord')], default='web', max_length=20)),
                ('buzz_date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tossup_buzzes', to='qsub.writer')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buzzes', to='qsub.playtestsession')),
                ('tossup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzzes', to='qsub.tossup')),
            ],
        ),
    ]
