# Generated by Django 6.0.2 on 2026-06-18 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0004_add_object_pk_is_removed_index'),
        ('qsub', '0014_playtestsession_bonusresult_tossupbuzz'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusresult',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tossupbuzz',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='DiscordCommentRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord_ref', to='django_comments.comment')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionset')),
            ],
        ),
        migrations.CreateModel(
            name='SetApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qsub.writer')),
                ('question_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='qsub.questionset')),
            ],
        ),
    ]
