# Generated by Django 6.0.2 on 2026-06-19 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0015_bonusresult_external_id_tossupbuzz_external_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bonus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_threads', to='qsub.bonus')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discord_threads', to='qsub.questionset')),
                ('tossup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_threads', to='qsub.tossup')),
            ],
        ),
    ]
