# Generated by Django 6.0.2 on 2026-06-20 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0016_discordthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusresult',
            name='bonus_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='qsub.bonushistory'),
        ),
        migrations.AddField(
            model_name='tossupbuzz',
            name='tossup_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buzzes', to='qsub.tossuphistory'),
        ),
    ]
