# Generated by Django 6.0.2 on 2026-06-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0017_bonusresult_bonus_history_tossupbuzz_tossup_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
