# Generated by Django 6.0.2 on 2026-06-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0018_packet_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
