# Generated by Django 6.0.2 on 2026-06-22 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0020_styleruledismissal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_role_groups', to='qsub.writer')),
                ('members', models.ManyToManyField(blank=True, related_name='role_groups', to='qsub.writer')),
            ],
        ),
        migrations.CreateModel(
            name='GroupRoleGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionset')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.writer')),
            ],
            options={
                'unique_together': {('question_set', 'writer', 'role')},
            },
        ),
        migrations.CreateModel(
            name='SetRoleGroupAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('editor', 'Editor'), ('writer', 'Writer')], max_length=10)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_group_assignments', to='qsub.questionset')),
                ('role_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_assignments', to='qsub.rolegroup')),
            ],
            options={
                'unique_together': {('question_set', 'role_group')},
            },
        ),
    ]
