# Generated by Django 6.0.2 on 2026-06-22 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0021_rolegroup_grouprolegrant_setrolegroupassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=10)),
                ('question_id', models.PositiveIntegerField()),
                ('field', models.CharField(max_length=40)),
                ('field_label', models.CharField(max_length=60)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='pending', max_length=10)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionset')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_suggestions', to='qsub.writer')),
                ('suggested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_edits', to='qsub.writer')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
