# Generated by Django 6.0.2 on 2026-06-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0022_suggestededit'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='disabled_style_rules',
            field=models.TextField(blank=True, default=''),
        ),
    ]
