# Generated by Django 6.0.2 on 2026-06-24 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0023_questionset_disabled_style_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketSlotVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('question_type', models.CharField(max_length=10)),
                ('category', models.TextField(blank=True, default='')),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.packet')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionset')),
            ],
            options={
                'unique_together': {('packet', 'question_number', 'question_type')},
            },
        ),
    ]
