# Generated by Django 6.0.2 on 2026-06-26 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0024_packetslotvacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_distributions', to='qsub.writer'),
        ),
    ]
