# Generated by Django 6.0.2 on 2026-06-28 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0025_distribution_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusresult',
            name='answered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tossupbuzz',
            name='buzz_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
