# Generated by Django 6.0.2 on 2026-07-01 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0026_alter_bonusresult_answered_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGrammarFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=10)),
                ('question_id', models.PositiveIntegerField()),
                ('severity', models.CharField(default='warning', max_length=10)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('suggestion', models.TextField(blank=True, default='')),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qsub.writer')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_grammar_findings', to='qsub.questionset')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
