# Generated by Django 6.0.2 on 2026-07-01 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0027_aigrammarfinding'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleGroupJoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_group_join_requests', to='qsub.writer')),
                ('role_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='qsub.rolegroup')),
            ],
            options={
                'ordering': ['created_date'],
                'unique_together': {('role_group', 'requester')},
            },
        ),
    ]
