# Generated by Django 6.0.2 on 2026-07-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0028_rolegroupjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tossupbuzz',
            name='superpowered',
            field=models.BooleanField(default=False),
        ),
    ]
