# Generated by Django 6.0.2 on 2026-07-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0029_tossupbuzz_superpowered'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigrammarfinding',
            name='kind',
            field=models.CharField(default='grammar', max_length=10),
        ),
    ]
