# Generated by Django 6.0.2 on 2026-07-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0030_aigrammarfinding_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='tossupbuzz',
            name='dont_know',
            field=models.BooleanField(default=False),
        ),
    ]
