# Generated by Django 6.0.2 on 2026-07-10 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0031_tossupbuzz_dont_know'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visit', models.DateTimeField()),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsub.questionset')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_visits', to='qsub.writer')),
            ],
            options={
                'unique_together': {('writer', 'question_set')},
            },
        ),
    ]
