# Generated by Django 6.0.2 on 2026-07-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0032_setvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='enable_superpower',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tossup',
            name='all_power',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
