# Generated by Django 6.0.2 on 2026-07-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0035_rolegroup_creator_is_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
