# Generated by Django 6.0.2 on 2026-07-29 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0036_distribution_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetJoinLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('default_role', models.CharField(choices=[('writer', 'Writer'), ('editor', 'Editor')], default='writer', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_join_links', to='qsub.writer')),
                ('question_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='join_link', to='qsub.questionset')),
            ],
        ),
        migrations.CreateModel(
            name='SetJoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('via_link', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='qsub.questionset')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_join_requests', to='qsub.writer')),
            ],
            options={
                'ordering': ['created_date'],
                'unique_together': {('question_set', 'requester')},
            },
        ),
    ]
