# Generated by Django 6.0.2 on 2026-07-31 17:40

from django.db import migrations, models


def publish_existing(apps, schema_editor):
    """Before this field existed, every distribution was offered to everyone in
    the create-a-set picker. Keep that true for the ones already out there —
    only newly created distributions start private."""
    apps.get_model('qsub', 'Distribution').objects.update(public=True)


def unpublish_all(apps, schema_editor):
    apps.get_model('qsub', 'Distribution').objects.update(public=False)


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0037_setjoinlink_setjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(publish_existing, unpublish_all),
    ]
