# Generated by Django 6.0.2 on 2026-07-31 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0038_distribution_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDataOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(choices=[('pron', 'Pronunciation guide'), ('answer', 'Answer line')], max_length=10)),
                ('key', models.CharField(max_length=300)),
                ('term', models.CharField(blank=True, default='', max_length=300)),
                ('value', models.TextField(blank=True, default='')),
                ('suppressed', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('changed_date', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_data_edits', to='qsub.writer')),
            ],
            options={
                'ordering': ['dataset', 'key'],
                'unique_together': {('dataset', 'key')},
            },
        ),
    ]
