# Generated by Django 6.0.2 on 2026-08-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0039_reference_data_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='guides_require_quotes',
            field=models.BooleanField(default=False),
        ),
    ]
