# Generated by Django 6.0.2 on 2026-08-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0040_questionset_guides_require_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='part1_answer_structure',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='part2_answer_structure',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='part3_answer_structure',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='questionset',
            name='structured_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tossup',
            name='tossup_answer_structure',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
