# Generated by Django 6.0.2 on 2026-08-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0041_bonus_part1_answer_structure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionset',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending review'), ('declined', 'Declined')], default='approved', max_length=10),
        ),
        migrations.AddField(
            model_name='writer',
            name='can_create_early',
            field=models.BooleanField(default=False),
        ),
    ]
