# Generated by Django 6.0.2 on 2026-08-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0042_questionset_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='email_on_discord_comments',
            field=models.BooleanField(default=True),
        ),
    ]
