# Generated by Django 6.0.2 on 2026-08-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0043_writer_email_on_discord_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('token', models.CharField(max_length=300)),
                ('accepted', models.PositiveIntegerField(default=0)),
                ('rejected', models.PositiveIntegerField(default=0)),
                ('last_action_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('code', 'token')},
            },
        ),
    ]
