# Generated by Django 6.0.2 on 2026-08-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0044_suggestionfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytag',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
