# Generated by Django 6.0.2 on 2026-08-21 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0045_categorytag_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_path', models.CharField(db_index=True, max_length=500)),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_comments', to='qsub.writer')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_comments', to='qsub.questionset')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
