# Generated by Django 6.0.2 on 2026-08-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0046_categorycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytag',
            name='num_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
