# Generated by Django 6.0.2 on 2026-08-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0047_categorytag_num_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytag',
            options={'ordering': ['category_path', 'group_name', 'sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='categorytag',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
