# Generated by Django 6.0.2 on 2026-08-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0048_categorytag_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='discord_show_first_clue',
            field=models.BooleanField(default=False),
        ),
    ]
