# Generated by Django 6.0.2 on 2026-08-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0049_questionset_discord_show_first_clue'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycomment',
            name='edited_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
