# Generated by Django 6.0.2 on 2026-08-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0050_categorycomment_edited_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytag',
            name='show_in_output',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionset',
            name='export_category_tags',
            field=models.BooleanField(default=True),
        ),
    ]
