# Generated by Django 6.0.2 on 2026-08-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0051_categorytag_show_in_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytag',
            name='max_bonuses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorytag',
            name='max_questions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorytag',
            name='max_tossups',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
