# Generated by Django 6.0.2 on 2026-08-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0052_categorytag_max_bonuses_categorytag_max_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytag',
            name='category_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
