# Generated by Django 6.0.2 on 2026-09-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0053_alter_categorytag_category_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='percategorywritersettings',
            name='activity_on_question_changes',
            field=models.BooleanField(default=False),
        ),
    ]
