# Generated by Django 6.0.2 on 2026-09-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0054_percategorywritersettings_activity_on_question_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='enable_duplicate_checks',
            field=models.BooleanField(default=True),
        ),
    ]
