# Generated by Django 6.0.2 on 2026-09-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0055_questionset_enable_duplicate_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='favicon_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
