# Generated by Django 6.0.2 on 2026-09-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0056_questionset_favicon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='question_table_columns',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='questionset',
            name='question_table_random_order',
            field=models.BooleanField(default=False),
        ),
    ]
