# Generated by Django 6.0.2 on 2026-09-04 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0057_questionset_question_table_columns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOrderConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=6)),
                ('source_id', models.PositiveIntegerField()),
                ('target_type', models.CharField(max_length=6)),
                ('target_id', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('before', 'must come in an earlier packet than'), ('after', 'must come in a later packet than'), ('apart', 'must be at least this many packets away from')], default='apart', max_length=8)),
                ('packets', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qsub.writer')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_constraints', to='qsub.questionset')),
            ],
            options={
                'indexes': [models.Index(fields=['question_set', 'source_type', 'source_id'], name='qsub_questi_questio_d9f94b_idx'), models.Index(fields=['question_set', 'target_type', 'target_id'], name='qsub_questi_questio_45b5a2_idx')],
            },
        ),
    ]
