# Generated by Django 6.0.2 on 2026-09-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0058_questionorderconstraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='author_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tossup',
            name='author_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
