# Generated by Django 6.0.2 on 2026-09-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0059_question_author_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='warn_missing_category_tags',
            field=models.BooleanField(default=True),
        ),
    ]
