# Generated by Django 6.0.2 on 2026-09-06 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0060_questionset_warn_missing_category_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITagSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=10)),
                ('question_id', models.PositiveIntegerField()),
                ('confidence', models.CharField(default='medium', max_length=10)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qsub.writer')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tag_suggestions', to='qsub.questionset')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='qsub.categorytag')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('question_type', 'question_id', 'tag')},
            },
        ),
    ]
