# Generated by Django 6.0.2 on 2026-09-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0061_aitagsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='search_in_new_tab',
            field=models.BooleanField(default=True),
        ),
    ]
