# Generated by Django 6.0.2 on 2026-09-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0062_writer_search_in_new_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionset',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
