# Generated by Django 6.0.2 on 2026-09-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0063_distribution_archived_questionset_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='header_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='questionset',
            name='first_packet_credits',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='questionset',
            name='packet_credits',
            field=models.TextField(blank=True, default=''),
        ),
    ]
