# Generated by Django 6.0.2 on 2026-09-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0064_packet_header_note_questionset_first_packet_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='skip_type_questions_preview',
            field=models.BooleanField(default=False),
        ),
    ]
