# Generated by Django 6.0.2 on 2026-09-22 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0065_questionset_skip_type_questions_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySuperGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categories', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qsub.writer')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_groups', to='qsub.questionset')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('question_set', 'name')},
            },
        ),
    ]
