# Generated by Django 6.0.2 on 2026-09-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0066_categorysupergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='discord_bold_power_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionset',
            name='discord_spoiler_chunk_max',
            field=models.PositiveIntegerField(blank=True, default=160),
        ),
    ]
