# Generated by Django 6.0.2 on 2026-09-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsub', '0067_questionset_discord_bold_power_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolegroup',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_role_groups', to='qsub.writer'),
        ),
    ]
