from django.urls import re_path, include
from django.views.generic import ListView
from qems2.qsub.views import *
from qems2.qsub.models import *
from qems2.qsub.api import api_ping, api_buzzes, api_bonus_results, api_comments, api_threads

import django

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),

    # accounts
    re_path(r'^accounts/forgot-username/$', forgot_username, name='forgot_username'),
    re_path(r'^accounts/', include('allauth.urls')),

    re_path(r'^main/$', main),
    re_path(r'^$', main),
    re_path(r'^request_to_join/$', request_to_join),
    re_path(r'^about/$', about),
    re_path(r'^help/$', help_page),
    re_path(r'^profile/$', profile),

    re_path(r'^question_sets/$', question_sets),
    re_path(r'^import_set/$', import_set),
    re_path(r'^import_packets/$', import_packets),
    re_path(r'^create_question_set/$', create_question_set),
    re_path(r'^edit_question_set/(?P<qset_id>[0-9]+)/$', edit_question_set),
    re_path(r'^packetize_set/(?P<qset_id>[0-9]+)/$', packetize_set),
    re_path(r'^packet_grid/(?P<qset_id>[0-9]+)/$', packet_grid),
    re_path(r'^move_packet_question/$', move_packet_question),
    re_path(r'^unassign_packet_question/$', unassign_packet_question),
    re_path(r'^assign_unpacketized/$', assign_unpacketized),
    re_path(r'^set_packet_order/$', set_packet_order),
    re_path(r'^view_packet/(?P<packet_id>[0-9]+)/$', view_packet),
    re_path(r'^packet_revision/(?P<packet_id>[0-9]+)/$', packet_revision),
    re_path(r'^packet_mp3/(?P<packet_id>[0-9]+)/$', packet_mp3),
    re_path(r'^packet_mp3_status/(?P<packet_id>[0-9]+)/$', packet_mp3_status),
    re_path(r'^reorder_packet_questions/$', reorder_packet_questions),
    re_path(r'^undo_packet_grid_change/$', undo_packet_grid_change),
    re_path(r'^packet_grid_log/(?P<qset_id>[0-9]+)/$', packet_grid_log),
    re_path(r'^activity/(?P<qset_id>[0-9]+)/$', activity),
    re_path(r'^recap/(?P<qset_id>[0-9]+)/$', recap),
    re_path(r'^play/(?P<qset_id>[0-9]+)/$', play),
    re_path(r'^record_buzz/$', record_buzz),
    re_path(r'^record_bonus_result/$', record_bonus_result),
    re_path(r'^api_access/(?P<qset_id>[0-9]+)/$', api_access),
    re_path(r'^generate_set_api_key/$', generate_set_api_key),

    # Discord-bot API (per-set key auth, see qsub/api.py)
    re_path(r'^api/v1/ping/?$', api_ping),
    re_path(r'^api/v1/buzzes/?$', api_buzzes),
    re_path(r'^api/v1/bonus_results/?$', api_bonus_results),
    re_path(r'^api/v1/comments/?$', api_comments),
    re_path(r'^api/v1/threads/?$', api_threads),
    re_path(r'^set_members/(?P<qset_id>[0-9]+)/$', set_members),
    re_path(r'^resolve_comment/$', resolve_comment),
    re_path(r'^packet_issues/(?P<packet_id>[0-9]+)/$', packet_issues),
    re_path(r'^style_check/(?P<qset_id>[0-9]+)/$', style_check),
    re_path(r'^packet_style_issues/(?P<packet_id>[0-9]+)/$', packet_style_issues),
    re_path(r'^live_char_count/$', live_char_count),
    re_path(r'^apply_style_fix/$', apply_style_fix),
    re_path(r'^dismiss_style_issue/$', dismiss_style_issue),
    re_path(r'^swap_candidates/$', swap_candidates),
    re_path(r'^category_tags/(?P<qset_id>[0-9]+)/$', category_tags),
    re_path(r'^distributions/$', distributions),
    re_path(r'^add_editor/(?P<qset_id>[0-9]+)/$', add_editor),
    re_path(r'^add_co_owner/(?P<qset_id>[0-9]+)/$', add_co_owner),
    re_path(r'^add_writer/(?P<qset_id>[0-9]+)/$', add_writer),
    re_path(r'^clone_distribution/(?P<dist_id>[0-9]+)/$', clone_distribution),
    re_path(r'^edit_distribution/(?P<dist_id>[0-9]+)/$', edit_distribution),
    re_path(r'^edit_distribution/$', edit_distribution),
    re_path(r'^edit_tiebreak/(?P<dist_id>[0-9]+)/$', edit_tiebreak),
    re_path(r'^edit_tiebreak/$', edit_tiebreak),
    re_path(r'^edit_set_distribution/(?P<qset_id>[0-9]+)/$', edit_set_distribution),
    re_path(r'^edit_set_tiebreak/(?P<qset_id>[0-9]+)/$', edit_set_tiebreak),
    re_path(r'^add_tossups/(?P<qset_id>[0-9]+)/$', add_tossups),
    re_path(r'^add_tossups/(?P<qset_id>[0-9]+)/(?P<packet_id>[0-9]+)/$', add_tossups),
    re_path(r'^edit_tossup/(?P<tossup_id>[0-9]+)/$', edit_tossup),
    re_path(r'^delete_tossup/$', delete_tossup),
    re_path(r'^add_bonuses/(?P<qset_id>[0-9]+)/(?P<bonus_type>.+)/$', add_bonuses),
    re_path(r'^add_bonuses/(?P<qset_id>[0-9]+)/(?P<bonus_type>.+)/(?P<packet_id>[0-9]+)/$', add_bonuses),
    re_path(r'^edit_bonus/(?P<bonus_id>[0-9]+)/$', edit_bonus),
    re_path(r'^delete_bonus/$', delete_bonus),
    re_path(r'^add_packets/(?P<qset_id>[0-9]+)/$', add_packets),
    re_path(r'^edit_packet/(?P<packet_id>[0-9]+)/$', edit_packet),
    re_path(r'^type_questions/$', type_questions),
    re_path(r'^type_questions/(?P<qset_id>[0-9]+)/$', type_questions),
    re_path(r'^type_questions_edit/(?P<question_type>.+)/(?P<question_id>[0-9]+)/$', type_questions_edit),
    re_path(r'^delete_packet/$', delete_packet),
    re_path(r'^settings/$', settings),
    re_path(r'^logout/$', logout_view),
    re_path(r'^categories/(?P<qset_id>[0-9]+)/(?P<category_id>[0-9]+)/$', categories),
    re_path(r'^top_category/(?P<qset_id>[0-9]+)/(?P<category_name>[^/]+)/$', top_category),
    re_path(r'^export_question_set/(?P<qset_id>[0-9]+)/(?P<output_format>.+)/$', export_question_set),
    re_path(r'^delete_writer/$', delete_writer),
    re_path(r'^delete_editor/$', delete_editor),
    re_path(r'^delete_co_owner/$', delete_co_owner),
    re_path(r'^delete_set/$', delete_set),
    re_path(r'^delete_comment/$', delete_comment),
    re_path(r'^post_comment/$', post_comment),
    re_path(r'^reply_to_comment/$', reply_to_comment),
    re_path(r'^add_anchored_comment/$', add_anchored_comment),
    re_path(r'^add_question_comment/$', add_question_comment),
    re_path(r'^delete_all_comments/$', delete_all_comments),
    re_path(r'^restore_tossup/$', restore_tossup),
    re_path(r'^restore_bonus/$', restore_bonus),
    re_path(r'^tossup_history/(?P<tossup_id>[0-9]+)/$', tossup_history),
    re_path(r'^bonus_history/(?P<bonus_id>[0-9]+)/$', bonus_history),
    re_path(r'^questions_remaining/(?P<qset_id>[0-9]+)/$', questions_remaining),
    re_path(r'^category_overview/(?P<qset_id>[0-9]+)/$', category_overview),
    re_path(r'^bulk_change_set/(?P<qset_id>[0-9]+)/$', bulk_change_set),
    re_path(r'^writer_question_set_settings/(?P<qset_id>[0-9]+)/$', writer_question_set_settings),
    re_path(r'^contributor/(?P<qset_id>[0-9]+)/(?P<writer_id>[0-9]+)/$', contributor),

    re_path(r'^upload_questions/(?P<qset_id>[0-9]+)/$', upload_questions),
    re_path(r'^complete_upload/$', complete_upload),
    re_path(r'^move_tossup/(?P<q_set_id>[0-9]+)/(?P<tossup_id>[0-9]+)/$', move_tossup),
    re_path(r'^move_bonus/(?P<q_set_id>[0-9]+)/(?P<bonus_id>[0-9]+)/$', move_bonus),
    re_path(r'^convert_tossup/$', convert_tossup),
    re_path(r'^convert_bonus/$', convert_bonus),
    re_path(r'^view_all_questions/(?P<qset_id>[0-9]+)/$', view_all_questions),
    re_path(r'^duplicate_check/(?P<qset_id>[0-9]+)/$', duplicate_check),
    re_path(r'^view_all_comments/(?P<qset_id>[0-9]+)/$', view_all_comments),
    re_path(r'^question_set_distribution/(?P<qset_id>[0-9]+)/$', question_set_distribution),

    # json calls
    re_path(r'^get_unassigned_tossups/$', get_unassigned_tossups),
    re_path(r'^get_unassigned_bonuses/$', get_unassigned_bonuses),
    re_path(r'^assign_tossups_to_packet/$', assign_tossups_to_packet),
    re_path(r'^assign_bonuses_to_packet/$', assign_bonuses_to_packet),
    re_path(r'^change_question_order/$', change_question_order),

    # commenting framework
    re_path(r'^comments/', include('django_comments.urls')),

    # search
    re_path(r'^search/$', search),
    re_path(r'^search/(?P<passed_qset_id>[0-9]+)/$', search),
]
